name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-lint-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - run: yarn
      - run: yarn build
