name: Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 22
          cache: "yarn"
      - run: yarn
      - run: yarn build
